optidatacloud/vue-advanced-chat

src/utils/markdown/index.js

* Ajusta para que os links enviados no Chat sejam `target=_blank`;
* Fixes #3 
* Enviar um link no Chat;
* Clicar nele;
* Verificar se ele será aberto em uma nova guia;

fix: Fixes link options having no effect

---

demo/src/ChatContainer.vue
src/lib/ChatWindow.vue
src/lib/RoomsList/RoomsList.scss
src/lib/RoomsList/RoomsList.vue
src/utils/filter-items.js

* Ajusta para que uma nova mensagem não desfaça o filtro de chats;
* Fixes #26 
* Acessar o Chat com dois usuários;
* Filtrar chats em um deles;
* Mandar uma mensagem com o outro usuário;
* Verificar que o filtro de chats não será desfeito;
* Filtrar nenhuma conversa;
* Ver que será mostrado o texto: "Nenhum conversa encontrada" (ver imagem acima);

fix: New message undoing chats filtering (issue #26)

---

src/lib/Room/RoomFooter/RoomFooter.vue
types/index.d.ts

* Ajusta para não exibir usuários que sairam do Chat na `tagging selection list`;
* O que acontecia antes é que tu ainda podia marcar alguém que tinha saido do Chat;
* resolves #53 
* Testar na issue do Chat;

feat: filter out users that leave room from tagging selection list (issue #53)

---

src/lib/Room/RoomMessage/RoomMessage.vue

- Fixes #59
Esta PR corrige o truncamento de mensagens longas para arquivos e mensagens deletadas.                                                                                                           
Testes devem ser efetuados no chat

redo: read more indication for files and deleted messages (issue #59, pr # 68)

---

demo/src/ChatContainer.vue
src/lib/ChatWindow.vue
src/lib/RoomsList/RoomsList.vue
src/lib/RoomsList/RoomsSearch/RoomsSearch.vue

* Ajustei para que o campo de busca apareça ao mesmo tempo com o loader (antes se o loader estava na tela o input de busca não aparecia);
* Adicionei o propriedade `customSearchRooms` que usei pra armazenar o resultado da pesquisa
* Preferi separar `rooms` de `customSearchRooms` por que facilitou a implementação no Chat;
* Removi a `roomsNotFoundMessage` (que adicionei a um tempo atrás) pq o VAC já tinha uma prop pra isso;
* Corrige um detalhe que fazia o evento `load-more-rooms` não ser disparado;
* fix #72;
* Testar aqui: https://github.com/optidatacloud/optiwork-chat/pull/752

feat: show search input when loading rooms

---

src/lib/Room/RoomMessage/RoomMessage.vue
src/lib/RoomsList/RoomCallContent/RoomCallContent.scss
src/lib/RoomsList/RoomsList.scss

- Fixes #70
Este PR corrige um problema encontrado nos testes da chamada do chat. Em telas pequenas, os botões de chamada acabavam ficando ocultos.
Não requer testes (testar na chamada do chat).

redo: fixes call buttons (issues #70, pr #75)

---

src/lib/ChatWindow.vue
src/lib/Room/Room.vue
src/lib/RoomsList/RoomsList.scss
src/lib/RoomsList/RoomsList.vue

* Ajustei para que os chats arquivados sejam passados em um array específico (isso deixou o tratamento mais simples);
* O fluxo dos arquivados envolve 1 evento e 2 propriedades:
* `show-archived-rooms`: usado para alternar entre as rooms "normais" e arquivadas;
* `archived-rooms`: array usado para armazenar as rooms arquivadas (preferi separar em outro array pq deixou as coisas simples);
* `click-archived-rooms`: evento que escuto quando a opção é clicada;
* resolves #74;
* Testar no pull request do Chat:
* https://github.com/optidatacloud/optiwork-chat/pull/764;

chore: Adjusts archived to handle pagination (issue #74)

---

src/lib/MediaPreview/MediaPreview.scss
src/lib/MediaPreview/MediaPreview.vue
src/lib/Room/RoomMessage/MessageFiles/MessageFiles.vue
src/utils/constants.js
src/utils/media-file.js

> Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/839
- Esse PR tem como objetivo exibir um modal para pré-visualizar arquivos do tipo PDF, removendo a necessidade do usuário de fazer o download do arquivo toda vez, similar ao preview já existente no drive.
- Captura de tela mostrando o preview do PDF:
- Faça o envio de qualquer arquivo do tipo PDF em uma conversa e clique sobre ele para visualizar.
Fix: #839

feat: preview pdf files (issue #839 pr #80)

---

src/lib/ChatWindow.vue
src/lib/Room/Room.vue
src/lib/Room/RoomMessage/RoomMessage.vue

> Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/860#issue-2406184469
- Esse PR adiciona a funcionalidade de clicar sobre o avatar de quem fez o envio da mensagem e mostrar as informações desse contato no menu lateral
- Captura de tela mostrando o painel lateral:
- Abra uma conversa com outra pessoa (individual ou em grupo) e clique sobre a foto/nome dela no topo da conversa, um menu lateral deve aparecer exibindo as informações desse contato.
Fix: https://github.com/optidatacloud/optiwork-chat/issues/860#issue-2406184469

feat: click on message avatar to open side menu (issue #860 pr #81)

---

src/lib/Room/Room.vue
src/lib/Room/RoomMessage/MessageActions/MessageActions.vue
src/styles/menu.scss

> Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/863
- Esse PR adiciona a funcionalidade de copiar o conteúdo de uma mensagem através do menu de ações.
- Captura de tela mostrando a ação de copiar:
- Abra uma conversa com outra pessoa (individual ou em grupo) e clique nas opções da mensagem, se a imagem contiver um conteúdo texto a botão estará disponível e ao clicar o conteúdo deve ser copiado para a área de transferência.
Fix: https://github.com/optidatacloud/optiwork-chat/issues/863

 feat: copy message text (issue #863 pr #82)

---

src/lib/MediaPreview/MediaPreview.vue

Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/938
- Adiciona um listener no modal de preview de mídias para poder navegar entre os previews utilizando as setas do teclado (`leftArrow` e `rightArrow`)
- Enviar várias imagens em uma conversa, abrir o preview de uma delas e clicar com as setas do teclado para esquerda e para a direita, as midias devem ser trocadas de acordo.
Fix: [#938](https://github.com/optidatacloud/optiwork-chat/issues/938)

feat: browse through medias using left and right arrows (issue #938 pr #94)

---

src/components/FormatMessage/FormatMessage.vue
src/utils/emoji/index.js

Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/396
- Adicionado um caso no código tratar emojis mais "complexos" (são formados por vários caracteres unicode).
- Aplica o aumento da fonte apenas quando a mensagem contém apenas um único emoji.
Fix: https://github.com/optidatacloud/optiwork-chat/issues/396

fix: improve emoji checking and only increase font with single emoji (issue #396 pr #97)

---

src/lib/RoomsList/RoomsList.vue

- Ajusta quando o ícone de `loading` é exibido para não confundir o usuário.
- Navegar entre os filtros e verificar se o ícone aparece quando não deveria.

fix: showing loading icon when not needed

---

src/lib/ChatWindow.vue
src/lib/Room/Room.vue
src/lib/Room/RoomFooter/RoomFooter.vue
src/lib/Room/RoomMessage/RoomMessage.vue

Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/967
- O problema era que a listagem de `rooms` passado para os componentes estava incompleto.
- Por exemplo, se vc scrollasse ou fizesse uma pesquisa no filtro de `groups` a paginação seria aplicada no filtro atual e ficaria com mais resultados do que o filtro `default`.
- Ao clicar nesse room (que estava paginado no filtro `groupRoomsCasted`, mas não em `roomCasted`) as informações desse room era buscado de `roomsCasted` o qual não continha o room recentemente carregado, fazendo com que os componentes `roomFooter` e `roomHeader` que precisavam dessa info não funcionassem corretamente (ficavam ou escondidos ou em brancos).
- Pesquisar por uma conversa em grupo antiga e tentar abrir ela, agora deve abrir corretamente e …

fix: group not loading properly (issue #967)

---

src/themes/index.js

- fixes [#1016](https://github.com/optidatacloud/optiwork-chat/issues/1016)
--- 
- Ajustei as cores do visualizador do Chat (no light e no dark mode);
- Nesse pr do `vue-advanced-chat` a única coisa que foi mudada foi o tom do roxo;
---
- Os testes estão em: https://github.com/optidatacloud/optiwork-chat/pull/1023

redo: adjusts in visualizer colors (issue #1016)

---

src/lib/Room/RoomMessage/RoomMessage.scss

- fixes [#1036](https://github.com/optidatacloud/optiwork-chat/issues/1036)
--- 
- Ajusta a cor da checkbox de mensagem encaminhada;
---
- Testar com https://github.com/optidatacloud/optiwork-chat/pull/1032;
- Verificar as cores do encaminhamento de mensagem estão condizentes (tanto no light quanto no dark theme);

styles: adjusts in forwarding messages bg color (issue #1036)

---

src/lib/Room/RoomFooter/RoomFiles/RoomFile/RoomFile.scss
src/lib/Room/RoomFooter/RoomFiles/RoomFile/RoomFile.vue
src/lib/Room/RoomFooter/RoomFiles/RoomFiles.scss
src/lib/Room/RoomFooter/RoomFiles/RoomFiles.vue
src/lib/Room/RoomFooter/RoomFooter.vue
src/lib/Room/RoomFooter/RoomMessageReply/RoomMessageReply.scss
src/lib/Room/RoomFooter/RoomMessageReply/RoomMessageReply.vue
src/lib/Room/RoomMessage/AudioPlayer/AudioControl/AudioControl.scss
src/lib/Room/RoomMessage/AudioPlayer/AudioPlayer.scss
src/lib/Room/RoomMessage/MessageFiles/MessageFile/MessageFile.scss
src/lib/Room/RoomMessage/MessageFiles/MessageFile/MessageFile.vue
src/lib/Room/RoomMessage/MessageFiles/MessageFiles.scss
src/lib/Room/RoomMessage/MessageReply/MessageReply.scss
src/lib/Room/RoomMessage/MessageReply/MessageReply.vue
src/lib/Room/RoomMessage/RoomMessage.scss
src/utils/adhoc.js
src/utils/data-validation.js

* Ajusta UI dos arquivos para que seja mostrado o nome, tipo do arquivo, tamanho e ícone conforme tipo (ver prévia);
* Isso foi ajustado nos componentes onde um arquivo aparece: na mensagem, ao anexar e na resposta de mensagem;
* fix #110;
* Modo claro:
* Modo escuro:
* Testar no pull request do Chat: https://github.com/optidatacloud/optiwork-chat/pull/1066;

ui: improves file ui (issue #110, pr #111)

---

src/lib/ChatWindow.vue
src/lib/Room/RoomFooter/RoomFiles/RoomFile/RoomFile.scss
src/lib/Room/RoomFooter/RoomFiles/RoomFile/RoomFile.vue
src/lib/Room/RoomMessage/MessageFiles/MessageFile/MessageFile.vue
src/lib/Room/RoomMessage/MessageFiles/MessageFiles.vue

* Ajusta para desabilitar o visualizador de arquivos do VAC visto que vamos usar o visualizador do Drive (🔝);
* Antes o VAC tinha um tratamento para arquivos `previewable` (`pdf` e `images`), removi esse trecho e propaguei o evento pro Chat (agora é ele que vai tratar esse fluxo);
* O Chat escuta esse arquivo e trata ele conforme a ação enviada (`view` ou `download`);
* Ajustei também a UI da lista de arquivos anexados do Drive (antes a lista desse tipo de arquivo não mostrava o tamanho e o tipo);
* fix #112;
* Antes:
* Depois:
* Anexar arquivos do Drive;
* Verificar se o arquivo anexado irá mostrar o tipo e o tamanho (ver prévia);

chore: disables file viewer (issue #112, pr #113)

---

src/lib/Room/RoomMessage/MessageFiles/MessageFile/MessageFile.vue

Este PR evita a exibição da tela de erro ao tentar abrir um documento antes que ele esteja completamente preparado para visualização ou download. Apliquei a mesma lógica usada no controle de envio de mensagens para garantir consistência na interface.
Agora, enquanto a mensagem exibe um único check (✅), o documento permanecerá inacessível. Assim que a mensagem for enviada e receber o double check (✅✅), o documento poderá ser baixado ou visualizado normalmente.
---
Reproduza o comportamento reportado na issue.
Verifique que os botões de visualizar/download só ficam disponíveis após os arquivos estarem prontos.
---
- Fix: https://github.com/optidatacloud/optiwork-chat/issues/1072

fix: file view error package (issue #1072)

---

src/lib/Room/RoomMessage/RoomMessage.vue

- Esse PR ajusta para que o nome seja buscado do lugar correto em grupos sem integração com o Whatsapp.
- Mensagens e arquivos devem corretamente ser exibidas entre dois usuários

redo: fix username display

---

src/lib/Room/RoomFooter/RoomUsersTag/RoomUsersTag.vue
src/lib/Room/RoomHeader/RoomHeader.vue
src/lib/Room/RoomMessage/RoomMessage.vue
src/lib/RoomsList/RoomCallContent/RoomCallContent.vue
src/lib/RoomsList/RoomContent/RoomContent.vue
vite.config.js

Resolve:
> - #114 
- Esse PR ajusta para que as imagens de avatar sejam exibidas usando uma tag `img` em vez de usar `backgroud-image: url(...)`, assim vamos poder fazer cache da foto de perfil do usuário e do avatar do grupo.
- Verificar todas as ocorrências de avatar de usuário/grupo e confirmar se estão todas sendo exibidas corretamente, posicionamento/alinhamento/distorção etc. A princípio tudo deve ter ficado inalterado na visão do usuário.
- Cabeçalho do chat (grupo/invidual)
- Menu de menções
- Ao lado da mensagem (minha e de outros)
- Listagem de conversas
- :warning: Também foi modificado um ícone de usuário relacionado às chamadas
Fix: #114

tweak: convert avatar to img tag (issue #114)

---

src/lib/Room/RoomMessage/RoomMessage.scss

Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/1158
- Esse PR ajusta um overflow no username em telas de tamanho reduzido.
| Antes | Depois |
| ---   |  ----  |
| ![image](https://github.com/user-attachments/assets/945d858f-8681-457f-82fc-c0029081f73a) | ![image](https://github.com/user-attachments/assets/a1289436-7f48-4242-8eea-4277cb78a536) |
Fix: https://github.com/optidatacloud/optiwork-chat/issues/1158

redo: message username text overflow (issue #1158)

---

src/lib/Room/RoomFooter/RoomFooter.vue

Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/1192
- Esse PR resolve um problema onde a tecla `enter` parava de funcionar após usar a opção de áudio.
- Interagir com o botão de gravar áudio e em seguida tentar enviar uma mensagens de texto usando a tecla enter.
Fix: https://github.com/optidatacloud/optiwork-chat/issues/1192

fix: enter key malfunction (issue #1192)

---

src/lib/Room/RoomFooter/RoomFooter.vue
src/lib/Room/RoomFooter/RoomUsersTag/RoomUsersTag.scss
src/lib/Room/RoomHeader/RoomHeader.scss
src/lib/Room/RoomMessage/RoomMessage.scss

Resolve:
> - #114 
- Esse ajusta um erro onde os avatares ficavam esticados
- Mesmo de https://github.com/optidatacloud/vue-advanced-chat/pull/123
Fix: #114

redo: fix avatar stretching (issue #114)

---

src/components/FormatMessage/FormatMessage.vue
src/lib/MediaPreview/MediaPreview.vue
src/lib/Room/RoomFooter/RoomFiles/RoomFile/RoomFile.vue
src/lib/Room/RoomMessage/MessageFiles/MessageFile/MessageFile.scss
src/lib/Room/RoomMessage/MessageFiles/MessageFile/MessageFile.vue
src/lib/Room/RoomMessage/MessageReply/MessageReply.scss
src/lib/Room/RoomMessage/MessageReply/MessageReply.vue
src/lib/Room/RoomMessage/RoomMessage.scss

Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/1174
- Esse PR substitui os `background-image` usados nos anexos/medias pela tag `<img />`, minha hipotese é que por estar como `background-image` o DOM atualizava ao receber uma nova mensagem e o background-image era reaplicado, refazendo a consulta, assim com a tag img o browser deve fazer a cache devidamente e o vue deve se entender ao atualizar.
- Verificar todas as ocorrências de anexos/preview de imagens, nenhuma deve estar distorcida, fora isso tudo deve permanecer igual.
- Exeplos de teste:
- enviar uma imagem no chat
- fazer reply nessa imagem
- ver ela na listagem da sidebar em `mídias, áudios e documentos` 
Fix: https://github.com/optidatacloud/optiwork-chat/issues/1174

refact/perf: replace background-image with img tag (issue #1174)
